version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run start:prod
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      # - JWT_SECRET=${JWT_SECRET}
      # - DATABASE_URL=${DATABASE_URL}
      # Make sure to inject all other required env variables here
    # No volume mount for source code to ensure compiled code is used
    networks:
      - green_sync_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - green_sync_network

networks:
  green_sync_network:
    driver: bridge
